// Connect only to a Firefox launched with a disposable test profile. Never use a personal browser session.
const assert=require('node:assert/strict'),fs=require('node:fs');require('tsx/cjs');
const {initialSave,openPack,reveal}=require('../lib/game.ts');const {CARDS}=require('../lib/cards.ts');
const {ALPHA_VERSION}=require('../lib/release.ts');
const key='tcg-faerie-v1',base=process.env.ALPHA_URL||'http://127.0.0.1:3100';
const socket=new WebSocket(process.env.FIREFOX_BIDI_URL||'ws://127.0.0.1:9225/session');let seq=0;const pending=new Map();let errors=[];let stage="initial";
socket.onmessage=e=>{const data=JSON.parse(e.data);if(data.id){const job=pending.get(data.id);if(job){pending.delete(data.id);if(data.type==='error')job.reject(Error(JSON.stringify(data)));else job.resolve(data.result);}}else if(data.method==='log.entryAdded'&&data.params.level==='error')errors.push({stage,...data.params});};
const command=(method,params={})=>new Promise((resolve,reject)=>{const id=++seq;pending.set(id,{resolve,reject});socket.send(JSON.stringify({id,method,params}));setTimeout(()=>{if(pending.has(id)){pending.delete(id);reject(Error('Timeout '+method));}},15000).unref();});
async function evaluate(context,expression){const response=await command('script.evaluate',{expression,target:{context},awaitPromise:true});if(response.type==='exception')throw Error(JSON.stringify(response.exceptionDetails));return response.result?.value;}
const delay=ms=>new Promise(r=>setTimeout(r,ms));
async function wait(context,expression){for(let i=0;i<60;i++){if(await evaluate(context,expression))return;await delay(100);}throw Error('Wait failed: '+expression);}
const click=(context,text)=>{stage='click '+text;return evaluate(context,`(()=>{const b=[...document.querySelectorAll('button')].find(b=>b.textContent.includes(${JSON.stringify(text)}));if(!b)throw Error('Missing button');b.click();return true;})()`);};
(async()=>{await new Promise((r,j)=>{socket.onopen=r;socket.onerror=j;});const session=await command('session.new',{capabilities:{}});console.log('Firefox',session.capabilities.browserVersion);await command('session.subscribe',{events:['log.entryAdded']});const user=await command('browser.createUserContext');
const {context}=await command('browsingContext.create',{type:'tab',userContext:user.userContext});await command('browsingContext.navigate',{context,url:base,wait:'complete'});await wait(context,`!!document.querySelector('.machine-button')`);
await click(context,'Éveiller le portail');await evaluate(context,`(()=>{const b=document.querySelector('.machine-button');for(let i=0;i<50;i++)b.click();return true;})()`);await delay(1100);
assert.equal(await evaluate(context,`JSON.parse(localStorage.getItem('${key}')).clicks`),50);
const s=initialSave();const fixture={...s,energy:100000,owned:Object.fromEntries(CARDS.map(c=>[c.id,6])),deck:['001','002','003','004','005','008'],ux:{...s.ux,introSeen:true,skipTips:true,motion:'reduce',sound:false}};
await click(context,'Paramètres');await evaluate(context,`(()=>{const dt=new DataTransfer();dt.items.add(new File([${JSON.stringify(JSON.stringify(fixture))}],'fixture.json',{type:'application/json'}));const input=document.querySelector('input[type=file]');input.files=dt.files;input.dispatchEvent(new Event('change',{bubbles:true}));return true;})()`);await wait(context,`[...document.querySelectorAll('button')].some(b=>b.textContent==='Confirmer le remplacement')`);await click(context,'Confirmer le remplacement');await wait(context,`!!document.querySelector('.machine-button')`);
await click(context,'Paramètres');await wait(context,`!!document.querySelector('dialog[open]')`);assert.equal(await evaluate(context,`document.querySelector('dialog').textContent.includes(${JSON.stringify(ALPHA_VERSION)})`),true);
await click(context,'Copier les diagnostics');await click(context,'Revenir au jeu');await click(context,'Collection');await wait(context,`document.querySelectorAll('.collection-grid>.card').length===60`);await delay(200);
assert.ok(await evaluate(context,`document.querySelectorAll('.card[data-offscreen=true]').length`)>20);
await evaluate(context,`document.querySelector('.inspect-button').click()`);await wait(context,`!!document.querySelector('.card-inspection[open]')`);await evaluate(context,`document.querySelector('.modal-close').click()`);await click(context,'Mon deck');await wait(context,`!!document.querySelector('.synergy-grid')`);await click(context,'Progression');await click(context,'La machine');
const other=await command('browsingContext.create',{type:'tab',userContext:user.userContext});await command('browsingContext.navigate',{context:other.context,url:base,wait:'complete'});await wait(other.context,`!!document.querySelector('.machine-button')`);await command('browsingContext.close',{context:other.context});
const interrupted=reveal(openPack(fixture,['001','005','007','008','009'],'paid'));await click(context,'Paramètres');await evaluate(context,`(()=>{const dt=new DataTransfer();dt.items.add(new File([${JSON.stringify(JSON.stringify(interrupted))}],'partial.json',{type:'application/json'}));const input=document.querySelector('input[type=file]');input.files=dt.files;input.dispatchEvent(new Event('change',{bubbles:true}));return true;})()`);await wait(context,`[...document.querySelectorAll('button')].some(b=>b.textContent==='Confirmer le remplacement')`);await click(context,'Confirmer le remplacement');
for(let i=0;i<5;i++){await wait(context,`!!document.querySelector('.po-view,.po-summary')`);if(await evaluate(context,`!!document.querySelector('.po-summary')`))break;await click(context,i===3?'Voir les cinq cartes':'Carte suivante');await delay(100);}
await wait(context,`!!document.querySelector('.po-summary-grid')`);assert.equal(await evaluate(context,`JSON.parse(localStorage.getItem('${key}')).revealed`),5);await click(context,'Retour à la machine');
await command('browsingContext.setViewport',{context,viewport:{width:390,height:844}});await click(context,'Collection');await wait(context,`!!document.querySelector('.collection-grid')`);assert.equal(await evaluate(context,'document.documentElement.scrollWidth<=innerWidth+1'),true);
const shot=await command('browsingContext.captureScreenshot',{context,origin:'viewport'});fs.writeFileSync('test-results/alpha-firefox.png',Buffer.from(shot.data,'base64'));
assert.equal(await evaluate(context,`fetch('/dev').then(r=>r.status)`),404);
assert.deepEqual(errors.filter(e=>e.source?.context===context),[]);fs.writeFileSync('test-results/alpha-firefox-report.json',JSON.stringify({browser:session.capabilities.browserVersion,checks:['onboarding','50 rapid clicks','settings diagnostics','60 cards','offscreen pause','inspection','deck','progression','two tabs','partial booster','390px','dev404'],errors},null,2));console.log('PASS Firefox actual engine',session.capabilities.browserVersion);await command('browser.removeUserContext',{userContext:user.userContext});await command('session.end');socket.close();
})().catch(async e=>{console.error(e);try{await command('session.end');}catch{}socket.close();process.exitCode=1;});
